### ISSUE TITLE
Redundant development of Pinyin-toolkit and Chinese-support-addon

### ISSUE THREAD

**Issue by ttempe** [chatch/pinyin-toolkit#3]
Hi Christophe,

OSPATH pointed out to me that you were working on porting the Anki1 Pinyin Toolkit to Anki2.

He and I have started something new, called the "Chinese support add-on". Please check out ttempe/chinese-support-addon. It takes advantage of Anki2's newer features, which makes it simpler to do things like colorization, and even allows to put hanzi, pinyin and colorization into the same field. There's no support for anki1 decks yet, though.

The Pinyin toolkit is a hefty piece of work, and I'm not claiming I can do better ; but maybe we can avoid to duplication efforts, for example by porting the Pinyin Toolkit's translation or graph features to Chinese support add-on instead of porting them to Anki2.

(also, the AwesomeTTS add-on may just be octets away from providing perfect speech support)

What do you think?

Have fun,

**Comment by chatch** [comment]
Hi ttempe,

I just tried to look at the new plugin. I copied it to my addons directory but I'm not seeing any functionality ... Are there menu items or should it auto populate fields based on the note/card expression?

Regards the pinyin toolkit plugin I think I'm not too far off completing the port to Anki2 already. The plugin IS a hefty peice of work I agree. Probably more complex then it needs to be... But it works, it's built, and I think porting features to the new addon would take more time then to get this codebase working ... So my thoughts are to plug on and finish this work.

That said.. starting a fresh is tempting. Because the codebase is full of historical problems and workarounds. It is a bit of a mess. My thoughts were to get it working in Anki2 then look at refactoring and cleaning it up after that. 

btw. the Anki2 features you mention it takes advantage of... What are these? New libraries or something? 

Chris.

**Comment by ttempe** [comment]
Le 16/10/2012 19:35, Chris Hatch a écrit :

> Hi ttempe,
> 
> I just tried to look at the new plugin. I copied it to my addons 
> directory but I'm not seeing any functionality ... Are there menu 
> items or should it auto populate fields based on the note/card expression?
> 
> Hi Chris,

did you read the instructions in the main file? (Tools->addons->Chinese 
support->Edit)
You need to use the model provided by the addon, and keep its original 
name. I added this restriction so as not to mess up people's Anki 1 decks.

(we'll have to figure out how to make that more seamless in the future).

It does auto-update the Hanzi fields, for now (translation should not be 
that hard. I had Pinyin Toolkit's Google Translate query working the 
other day ; but I really like having an off-line dictionary, so I've 
disabled it while I work on it.

> Regards the pinyin toolkit plugin I think I'm not too far off 
> completing the port to Anki2 already. The plugin IS a hefty peice of 
> work I agree. Probably more complex then it needs to be... But it 
> works, it's built, and I think porting features to the new addon would 
> take more time then to get this codebase working ... So my thoughts 
> are to plug on and finish this work.
> 
> OK.
> I'll keep doing my stuff, but I'll probably steal parts from you.
> 
> That said.. starting a fresh is tempting. Because the codebase is full 
> of historical problems and workarounds. It is a bit of a mess. My 
> thoughts were to get it working in Anki2 then look at refactoring and 
> cleaning it up after that.
> 
> I came to the same conclusion. I wonder how the original authors came to 
> writing a logging facility inside the plug-in.
> 
> btw. the Anki2 features you mention it takes advantage of... What are 
> these? New libraries or something?
> 
> The ability to auto-generate cards if needed.
> I don't know how far you've been studying Chinese, but my deck is 
> plagued with synonyms and alternate spellings, which I can't represent 
> nicely in Anki 1. Here, I have four "Hanzi" fields, and Anki generates 
> up to four "recognition" and four "recall" cards, depending on how many 
> I fill in.

Colorization is done through CSS. OSPATH simply specified a HTML class 
for each tone in the plugin, and the user can reconfigure the colors 
through the CSS code for the model, no need for special UI configuration 
feature.

Also (and this may have been present in Anki1, but not taken advantage 
of), thanks to OSPATH's design, I use only one field to store the hanzi, 
the pinyin, and the coloring. I then use templates (eg: 
{{Pinyin_notone:Hanzi1}}, or {{Hanzi_text:Hanzi1}} to extract just what 
I need from that field, and present it my cards.

I even have a template that shows all the alternate Hanzi for one note, 
but hide the hanzi in common. I put it on the recall cards, to help the 
user identify a word out of a set of synonyms.

This is working right now. I'm pretty happy with it. I plan to push it 
upstream to libanki, so it also works with the mobile clients.

I took over development from OSPATH. I just published a new version into 
Anki's plugin repository 24 hours ago, you can install it directly from 
within Anki.

Have fun,

## 

Thomas TEMPÉ

**Comment by chatch** [comment]
Hi Thomas,

I just took a look at the latest version of Chinese Support addon. Looks good. Meanings lookup is fast from the editing form hey? I like the dictionary download on language selection too. Works really well.

A question about the model. Do you know can decks with other models be converted to use this model without losing all the deck history and statistics...? It's not something I've done before with my decks but I guess if the core fact/note expression field is preserved it should be possible... When the support addon has more features it would be nice to move my deck over and work with it for a bit. Also I have some smaller decks I would like to try now.

I'm still plugging along with porting the toolkit plugin... I want to get most of the functionality that I was using in Anki 1 working in Anki 2 so I can use that stuff ASAP. But it's continuing to take longer then I expected ... TT That said the bulk updates stuff is working so I'll prob. release a version soon.

After that I don't know... Maybe I can help you port some features to Chinese support addon and think about this issue of 2 code bases.

Cheers,
Chris.

**Comment by chatch** [comment]
hmmm... looks like you can't run both plugins side by side too ... some kind of clash in cjklib..

will look into this another time. just one at a time for now.

**Comment by ttempe** [comment]
Le 28/10/2012 11:49, Chris Hatch a écrit :

> Hi Thomas,
> 
> I just took a look at the latest version of Chinese Support addon. 
> Looks good. Meanings lookup is fast from the editing form hey? I like 
> the dictionary download on language selection too. Works really well.
> 
> Thank you.
> 
> A question about the model. Do you know can decks with other models be 
> converted to use this model without losing all the deck history and 
> statistics...?

It could be achieved by :
- copying the new templates to the old model
- renaming all the fields accordingly
- (manually?) updating all hanzi fields to furigana notation, and 
  checking the pinyin to see if it's still right.

However, if one were to use the new input features on an old deck, they 
would mess his fields badly. Therefore, I've disabled them for notes not 
created from the Chinese Support Add-on model (in edit.py, in function 
on_focus_lost).

I'm upset about it myself, as my existing deck is pretty big by now and 
I'd love to use synonym support.

Right now, existing decks will still display properly in Anki2, but 
they'll be missing the editing features.

I'll consider the question again after I've stabilized other aspects of 
the plug-in.

> I'm still plugging along with porting the toolkit plugin... I want to 
> get most of the functionality that I was using in Anki 1 working in 
> Anki 2 so I can use that stuff ASAP. But it's continuing to take 
> longer then I expected ... TT That said the bulk updates stuff is 
> working so I'll prob. release a version soon. 
> Getting to understand an existing codebase takes a lot of time, I can 
> testify.

Once you upload it to ankiweb, drop me a note so I can mention it on my 
plugin description.

> After that I don't know... Maybe I can help you port some features to 
> Chinese support addon and think about this issue of 2 code bases.
> 
> Good idea.

Have fun.

## 

Thomas TEMPÉ

**Comment by ttempe** [comment]
Le 28/10/2012 12:54, Chris Hatch a écrit :

> hmmm... looks like you can't run both plugins side by side too ... 
> some kind of clash in cjklib..
> 
> will look into this another time. just one at a time for now.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/chatch/pinyin-toolkit/issues/3#issuecomment-9842758.
> 
> FYI, I incorporated a copy of cjklib 0.3.2 in Chinese Support Addon.

## 

Thomas TEMPÉ

**Comment by chatch** [comment]
Heya ttempe, I finally got a version of this working. I've tested on Linux and Windows with the chinese-support-addon running side by side and it seems fine. This is pretty handy to switch as needed. But requires model name changes. That is to say chinese-support-addon working on any models with 'Chinese' and Pinyin plugin working on 'Mandarin'. This string 'Mandarin' is configurable in the Pinyin toolkit preferences on the Model tab. 

I still don't have stats and graphs working so still not sure how much effort there is in moving that over to chinese support addon. Moving stuff that's already up and running tho should be pretty easy .. Because It's all working with the right versions of Python, SQLAlchemy, Anki 2 core libs, etc.

**Comment by ttempe** [comment]
Good job, Chris.

I haven't got the stats up either.
Push it up on Ankiweb, and we'll see who wins.
I'll mention it on the plugin's description when I get around to publishing a new version.

Have fun,

Thomas

**Comment by ttempe** [comment]
Le 23/02/13 16:37, Chris Hatch a écrit :

> Heya ttempe, I finally got a version of this working. I've tested on
> Linux and Windows with the chinese-support-addon running side by side
> and it seems fine. This is pretty handy to switch as needed. But
> requires model name changes. That is to say chinese-support-addon
> working on any models with 'Chinese' and Pinyin plugin working on
> 'Mandarin'. This string 'Mandarin' is configurable in the Pinyin
> toolkit preferences on the Model tab.
> 
> I still don't have stats and graphs working so still not sure how much
> effort there is in moving that over to chinese support addon. Moving
> stuff that's already up and running tho should be pretty easy ..
> Because It's all working with the right versions of Python,
> SQLAlchemy, Anki 2 core libs, etc.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chatch/pinyin-toolkit/issues/3#issuecomment-13987083.
> 
> Good work, Chris.

I haven't got the stats up either.
Push it up on Ankiweb, and we'll see who wins.

Have fun,

Thomas

**Comment by chatch** [comment]
Hi Thomas, it's up there now "Pinyin Toolkit"
